# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      PR_TITLE: ${{github.event.pull_request.title}}

#     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run:  echo ${{env.PR_TITLE}}

# Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{env.filepath}}
          echo ${{env.files}}
        env: 
          filepath: "some path"
          files: this-$filepath- ++
                  
      - name: Bump Version and Push Tag
        id: prj_ver_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          custom_tag: "dev/latest"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a Github Release Version
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.prj_ver_tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Fetch dev
        id: fetch-dev
        continue-on-error: true
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "vdev/latest"
          file: "Source code.zip"
          target: "./"
          token: ${{ secrets.GITHUB_TOKEN }}
