# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - edited
      - synchronize

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      PR_TITLE: ${{github.event.pull_request.title}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
      
    - run:  echo ${{env.PR_TITLE}}
    - name: Check if Pull Request title contains Jira ID
      run: |
        JIRA_ID=$(echo "${{env.PR_TITLE}}" | grep -o -E '([a-zA-Z]{1,10})+\-([0-9]{1,8})' | sed 's/^/"/;s/$/"/' | paste -sd, -)
        if [ -z "${JIRA_ID}" ]; then
          echo "PR title should have JIRA ID's. eg: feat: tst-454 add pr jira id linter"
          exit 1
        fi

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
